package basic;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class demo {

@Test
/*	public static void main(String args[]) {
*/		public static void test1() {
	System.out.println("Anand");
	/*	WebDriver driver = new FirefoxDriver();*/
     
		System.setProperty("webdriver.gecko.driver", "I:/Workspaces/geckodriver.exe");
		DesiredCapabilities capabilities = DesiredCapabilities.firefox();
		capabilities.setCapability("marionette", true);
		WebDriver driver = new FirefoxDriver();
      driver.get("https:\\www.google.com");
    }
	
/*	 @BeforeClass
	    public void setup()
	    {
	        System.out.println("I am in Setup");
	    }

	    @Test
	    public void test()
	    {
	        System.out.println("I am in Test");
	    }

	    @AfterClass
	    public void tearDown()
	    {
	        System.out.println("I am in tearDown");
	    }*/
}

